import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { apiClient } from './apiClient';

export type AnalyticsEvent =
  | { name: 'convoy_started'; props: { groupSize: number } }
  | { name: 'convoy_ended'; props: { durationMin: number; distanceKm: number } }
  | { name: 'ptt_used'; props: { durationSec: number } }
  | { name: 'hazard_reported'; props: { type: string } }
  | { name: 'group_created'; props: Record<string, never> }
  | { name: 'group_joined'; props: Record<string, never> }
  | { name: 'waypoint_added'; props: { type: string } }
  | { name: 'event_rsvp'; props: { status: string } }
  | { name: 'friend_added'; props: Record<string, never> }
  | { name: 'screen_viewed'; props: { screen: string } }
  | { name: 'share_triggered'; props: { surface: string } }
  | { name: 'notification_tapped'; props: { type: string } }
  | { name: 'map_style_changed'; props: { style: string } };

const QUEUE_KEY = '@convoy/analytics_queue';
const ANON_ID_KEY = '@convoy/anon_id';
const MAX_QUEUE = 50;
const FLUSH_AT = 10;


class Analytics {
  private queue: Array<{
    id: string;
    event: string;
    props: Record<string, unknown>;
    ts: number;
  }> = [];
  private flushing = false;
  private anonymousId: string | null = null;
  private initialized = false;
  /** Bumped by reset() so an in-flight flush knows its queue was discarded. */
  private generation = 0;

  async init(): Promise<void> {
    if (this.initialized) return;
    this.initialized = true;

    let id = await AsyncStorage.getItem(ANON_ID_KEY);
    if (!id) {
      id = Math.random().toString(36).substring(2) + Date.now().toString(36);
      await AsyncStorage.setItem(ANON_ID_KEY, id);
    }
    this.anonymousId = id;

    const saved = await AsyncStorage.getItem(QUEUE_KEY);
    if (saved) {
      try { this.queue = JSON.parse(saved) as typeof this.queue; } catch { this.queue = []; }
      // Entries written by a build predating the dedupe id have none. They are
      // the likeliest of all to be double-counted — surviving on disk is what
      // an app-kill replay is made of — so stamp them now and write the ids
      // back, making them stable for every later restore.
      const missing = this.queue.filter((e) => !e.id);
      if (missing.length > 0) {
        for (const entry of missing) {
          entry.id = Math.random().toString(36).slice(2) + Date.now().toString(36);
        }
        await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(this.queue)).catch(() => {});
      }
    }
  }

  track(event: AnalyticsEvent): void {
    const entry = {
      // Stamped HERE, when the event happens — not in flush(). That is the
      // whole point: a batch whose response was lost goes back on the queue
      // and is sent again, and only an id fixed at record time lets the server
      // recognise the second delivery as the same events (migration 039).
      // Minting it per-send would make every retry look like new activity.
      id: Math.random().toString(36).slice(2) + Date.now().toString(36),
      event: event.name,
      props: event.props as Record<string, unknown>,
      ts: Date.now(),
    };
    this.queue.push(entry);
    if (this.queue.length > MAX_QUEUE) this.queue.shift();
    AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(this.queue)).catch(() => {});
    if (this.queue.length >= FLUSH_AT) void this.flush();
  }

  screen(name: string): void {
    this.track({ name: 'screen_viewed', props: { screen: name } });
  }

  /**
   * Drop every queued event and the persisted copy. Called on sign-out: the
   * queue holds events generated by the account that is leaving, but `flush()`
   * sends it with whatever bearer token apiClient injects at the time, so
   * anything left behind is POSTed under the NEXT account's token and recorded
   * against their userId.
   *
   * Clearing the in-memory array is not optional — this singleton outlives
   * sign-out, so removing only the storage key leaves the same events in
   * memory for the next `track()` to persist straight back again.
   *
   * Losing a handful of unsent events is the right trade: sign-out has to work
   * offline, so flushing them first is not an option. `@convoy/anon_id` is
   * deliberately left alone — it identifies the device, not the person.
   */
  async reset(): Promise<void> {
    this.generation += 1; // invalidate any in-flight flush
    this.queue = [];
    await AsyncStorage.removeItem(QUEUE_KEY).catch(() => {});
  }

  async flush(): Promise<void> {
    if (this.flushing || this.queue.length === 0) return;
    this.flushing = true;
    const generation = this.generation;
    const batch = this.queue.splice(0, 20);
    try {
      await apiClient.post('/api/v1/analytics/events', {
        anonymousId: this.anonymousId,
        platform: Platform.OS,
        events: batch,
      });
      // A sign-out that landed while this POST was in flight already cleared
      // the queue; writing here would persist the leaving account's remaining
      // events straight back into the next account's queue.
      if (generation !== this.generation) return;
      await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(this.queue));
    } catch {
      // Same reasoning, and worse: the un-sent batch itself would be restored.
      if (generation !== this.generation) return;
      this.queue = [...batch, ...this.queue].slice(0, MAX_QUEUE);
    } finally {
      this.flushing = false;
    }
  }
}

export const analytics = new Analytics();
